---
- name: Install vector for centos8
  ansible.builtin.import_tasks: centos8.yml
  when: ansible_facts['os_family'] == "RedHat"
- name: Install vector for ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == "Debian"